# Generated by Django 3.1.4 on 2020-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMProduct',
            fields=[
                ('reference', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('brand_id', models.CharField(max_length=30)),
            ],
        ),
    ]
